/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./app-button.vue')['default']
    AppCard: typeof import('./app-card.vue')['default']
    AppDialog: typeof import('./app-dialog.vue')['default']
    AppIcon: typeof import('./app-icon.vue')['default']
    AppInput: typeof import('./app-input.vue')['default']
    AppPagination: typeof import('./app-pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
